apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagy-illes-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nagy-illes-frontend
  template:
    metadata:
      labels:
        component: nagy-illes-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/jedlik-gyor/nagyilles-frontend:1.0.4
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: jedlik-gyor-ghcr-io-registry-secret
                       
---

apiVersion: v1
kind: Service
metadata:
  name: nagy-illes-frontend-cluster-ip-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    component: nagy-illes-frontend
    
---    

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nagy-illes-frontend-ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    
spec:
  tls:
    - hosts:
        - nagyilles.jedlik.cloud
      secretName: cluster-jedlik-eu
  rules:
    - host: nagyilles.jedlik.cloud
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: nagy-illes-frontend-cluster-ip-service
                port:
                  number: 80