export * from './home/home.component';
export * from './lists/lists.component';
export * from './nav/nav.component';
export * from './news/news.component';
export * from './register/register.component';
export * from './app.component';
export * from './profile-edit/profile-edit.component'
export * from './users/user-list/user-list.component';
export * from './admin-configuration/admin-configuration.component'